{% set name = "i-pi" %}
{% set version = "3.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/ipi/ipi-{{ version }}.tar.gz
  sha256: ce6ec9c4ade32da305f71426a808346f750633e45e51b05851382edd6b6748dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - ipi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://ipi-code.org
  license: MIT
  license_family: MIT
  license_file: licenses/license_MIT.txt
  summary: 'i-PI: a universal force engine'
  description: |
    i-PI is a universal force engine interface written in Python, designed
    to be used together with an ab-initio (or force-field based) 
    evaluation of the interactions between the atoms. The main goal is to
    decouple the problem of evolving the ionic positions to sample the
    appropriate thermodynamic ensemble and the problem of computing the
    inter-atomic forces.
  doc_url: https://ipi-code.org/i-pi/
  dev_url: https://github.com/i-pi/i-pi

extra:
  recipe-maintainers:
    - jan-janssen
